### ISSUE TITLE
SWIG PCRE etc.

### ISSUE THREAD

**Issue by bstemper** [vollib/vollib#3]
As is stated in the Readme, in order to get vollib to run, an installation of SWIG is required which in turn needs PCRE to be installed. On my Mac, I found it non-trivial to find the right packages and to get them installed. On the other hand, installing SWIG/PCRE via Homebrew is idiot-proof:

1. Installation of homebrew via a one-liner pasted from their website to your terminal
2. Running 'brew install swig' on your terminal, installing PCRE as a dependency automatically.

If you don't mind, I would update the readme accordingly.

**Comment by iotatx** [comment]
Thank you Ben.  That is most helpful information.  Will make sure to follow your suggestion!
