### ISSUE TITLE
unable to find vcvarsall.bat

### ISSUE THREAD

**Issue by tony21248772** [vollib/vollib#4]
win7 64,vs2010,vs2008,pycharm,python3.5
python3 -m pip install lets_be_rational

i got the swig.exe -python -outdir lets_be_rational -o ....
error: unable to find vcvarsall.bat
then i download source code from GitHub, 
python3 setup.py build , i got the same error 
how to fix ????

**Comment by iotatx** [comment]
So far neither we (the project sponsors) nor any contributors have worked on support for Python 3.  That is one request we’ve had, though, so it’s queued up in our “TODO” list.
